Django/02 Social Media Project/App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name = 'sign_up'),
    path('login/', views.login_page, name='login'),
    path('edit/', views.edit_profile, name='edit'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
]

Django/02 Social Media Project/App_Posts/urls.py
from django.urls import path
from App_Posts import views

app_name = 'App_Posts'

urlpatterns = [
    path('', views.Home, name='home'),
]

Django/02 Social Media Project/My_Social_Media/urls.py
from django.contrib import admin
from django.urls import path, include

from App_Posts import views

# for media files
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_Posts.urls')),
    path('', views.Home, name='home'),
]
#for media files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/02 Social Media Project/App_Login/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    dob = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)

class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    follow = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created_date = models.DateTimeField(auto_now_add=True)

Django/02 Social Media Project/App_Posts/models.py
from distutils.command.upload import upload
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    image = models.ImageField(upload_to = 'post_images')
    caption = models.CharField(max_length=200, blank=True)
    upload_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['-upload_date',]

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='liked_post')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker')
    date_created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return '{} : {}'.format(self.user, self.post)

Django/02 Social Media Project/App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User

from App_Login.models import UserProfile

class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True, label="",
                             widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    username = forms.CharField(required=True, label="",
                               widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password1 = forms.CharField(required=True, label="",
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(required=True, label="",
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm your password'}))
    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')
class EditProfile(forms.ModelForm):
    dob = forms.DateField(widget=forms.TextInput(attrs={'type':'date',}))
    class Meta:
        model = UserProfile
        exclude = ('user',)

Django/02 Social Media Project/App_Login/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from App_Login.forms import CreateNewUser,EditProfile
from django.contrib.auth.forms import AuthenticationForm

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from App_Login.models import UserProfile

def sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method == 'POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('App_Login:login'))
    return render(request, 'App_Login/signup.html', context={'title': 'Signup page', 'form': form})

def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('App_Posts:home'))
    return render(request, 'App_Login/login.html', context={'title': 'Login', 'form':form})

@login_required
def edit_profile(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)
    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            form = EditProfile(instance=current_user)
    return render(request,'App_Login/profile.html', context={'title': 'Edit Profile', 'form':form})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:login'))

@login_required
def profile(request):
    return render(request, 'App_Login/user.html', context={'title':'User Profile'})

Django/02 Social Media Project/App_Posts/views.py
from django.shortcuts import render

from django.contrib.auth.decorators import login_required

@login_required
def Home(request):
    return render(request,'App_Posts/home.html', context={'title': 'Home'})

Django/02 Social Media Project/templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}  {{title}}  {% endblock %}

{% block body_block %}

<h1>Login Here</h1>
<form method="POST">
    {{form | crispy}}
    {% csrf_token %}
    <button type="submit" style="width:100%" class="btn btn-primary">Login</button>
</form>
<br>
<div>
    <p>Have an Account? <a href="{% url 'App_Login:sign_up' %}">Signup here</a></p>
</div>
{% endblock %}

Django/02 Social Media Project/templates/App_Login/profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %}  {{title}}  {% endblock %}

{% block body_block %}

<form method="POST" enctype="multipart/form-data">
    {{form | crispy}}
    {% csrf_token %}
    <button type="submit" name="button" style="width:100%" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

Django/02 Social Media Project/templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}  {{title}}  {% endblock %}

{% block body_block %}
<h1>Sign Up to our Social Media</h1>
<form method="POST">
    {{form | crispy}}
    {% csrf_token %}
    <button type="submit" style="width:100%" class="btn btn-primary">Signup</button>
</form>
<br>
<div>
    <p>Have an Account? <a href="{% url 'App_Login:login' %}">Login here</a></p>
</div>
{% endblock %}

Django/02 Social Media Project/templates/App_Login/user.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %}  {{title}}  {% endblock %}

{% block body_block %}
<h1>User Profile Page</h1>
{% endblock %}