Django/01 Blog Project/App_Blog/urls.py
from django.urls import path
from . import views
app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('detail/<int:blog_id>/', views.blog_details,name='blog_details'),

    path('liked/<int:blog_id>/',views.liked, name='liked_post'),
    path('unliked/<int:blog_id>/',views.unliked, name='unliked_post'),

    path('my-blogs/', views.MyBlog.as_view(), name='my_blogs'),
    path('edit/<int:pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
]

Django/01 Blog Project/App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name = 'login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-profile/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add-picture/', views.add_pro_pic, name = 'add_pro_pic'),
    path('change-picture/', views.change_pro_pic, name = 'change_pro_pic'),
]

Django/01 Blog Project/My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

# for images
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.Index, name='index')
]

#for images
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/01 Blog Project/App_Login/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pics')

Django/01 Blog Project/App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from App_Login.models import UserProfile


# Overiding django forms...i am adding email fiels.

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')


class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic', ]

Django/01 Blog Project/App_Login/views.py
from django.shortcuts import render

from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from App_Login.forms import SignUpForm, UserProfileChange, ProfilePic

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.shortcuts import HttpResponseRedirect
from django.urls import reverse


def sign_up(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
    dict = {'form': form, 'registered': registered}
    return render(request, 'App_Login/signup.html', context=dict)


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:  # if user exists
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    return render(request, 'App_Login/login.html', context={'form': form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def profile(request):
    return render(request, 'App_Login/profile.html', context={})


@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)
    return render(request, 'App_Login/change_profile.html', context={'form': form})


@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'App_Login/pass_change.html', context={'form': form, 'changed': changed})


@login_required
def add_pro_pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/pro_pic_add.html', context={'form': form})


@login_required
def change_pro_pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/pro_pic_add.html', context={'form': form})

Django/01 Blog Project/templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Change Profile {% endblock %}
{% block body_block %}

<h2>Change Form</h2>
<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}
<button type="submit" class="btn btn-warning btn-sm">Change Form</button>
</form>

{% endblock %}

Django/01 Blog Project/templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}
{% block body_block %}

<h2>Login</h2>
<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}
<button type="submit" class="btn btn-primary btn-sm">Login</button>
</form>

{% endblock %}

Django/01 Blog Project/templates/App_Login/pass_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Change Password {% endblock %}
{% block body_block %}

<h2>Change Password</h2>
{% if changed %}
<div class="alert alert-success">Password Change Successfully</div>
{% else %}
<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}
<button type="submit" class="btn btn-warning btn-sm">Change Password</button>
</form>
{% endif %}
{% endblock %}

Django/01 Blog Project/templates/App_Login/pro_pic_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Profile {% endblock %}
{% block body_block %}

<h2>Add your Profile Picture</h2>
<form method="POST" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Add</button>
</form>

{% endblock %}

Django/01 Blog Project/templates/App_Login/profile.html
{% extends 'base.html' %}
{% block title_block %} Profile {% endblock %}
{% block body_block %}

<h2>Your Profile</h2>
{% if user.user_profile %}
    <img src="/media/{{ user.user_profile.profile_pic }}" class="rounded-circle" width="100px">
    <br>
    <a href="{% url 'App_Login:change_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>
{% else %}
    <img src="/media/profile_pics/avatar-male.jpg" class="rounded-circle" width="100px">
    <br>
    <a href="{% url 'App_Login:add_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>
{% endif %}
    <p>Username: {{user.username}}</p>
    <p>Email: {{user.email}}</p>
    <p>Name: {{user.first_name}} {{user.last_name}}</p>
<br>
    <a href="{% url 'App_Login:user_change' %}" class="btn btn-warning btn-sm">Change Profile Info</a>

{% endblock %}

Django/01 Blog Project/templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Create New Account {% endblock %}
{% block body_block %}

{% if registered %}
<div class="alert alert-success">
Account Created Successfully ! <a href="{% url 'App_Login:login' %}">Login Here</a>
</div>
{% else %}
<h2>Create New Account</h2>
<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Create Account</button>
</form>
<br>
<p>Already have an account? <a href="{% url 'App_Login:login' %}"> Login Here</a></p>
{% endif %}
{% endblock %}