Django/01 Blog Project/App_Blog/urls.py
from django.urls import path
from . import views
app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('detail/<int:blog_id>/', views.blog_details,name='blog_details'),

    path('liked/<int:blog_id>/',views.liked, name='liked_post'),
    path('unliked/<int:blog_id>/',views.unliked, name='unliked_post'),

    path('my-blogs/', views.MyBlog.as_view(), name='my_blogs'),
    path('edit/<int:pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
]

Django/01 Blog Project/App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name = 'login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-profile/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add-picture/', views.add_pro_pic, name = 'add_pro_pic'),
    path('change-picture/', views.change_pro_pic, name = 'change_pro_pic'),
]

Django/01 Blog Project/My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

# for images
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.Index, name='index')
]

#for images
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/01 Blog Project/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" rel="stylesheet">

    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

    <title>{% block title_block %} Blog {% endblock %}</title>
  </head>

<body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark ">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}"><img src="/media/logo.png" width="50px"></a>
      </li>
      {% if user.is_authenticated %}
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{user.username}}
        </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Your Profile</a>
            <a class="dropdown-item" href="{% url 'App_Blog:create_blog' %}">Create Blog</a>
            <a class="dropdown-item" href="{% url 'App_Blog:my_blogs' %}">My Blogs</a>
            <br>
            <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
          </div>
      </div>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'App_Login:signup' %}">Signup</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
      </li>
      {% endif %}
    </ul>
  </nav>
<div class="container" style="padding-top:20px">
  {% block body_block %}


  {% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>